 .gitignore                                       |    1 [32m+[m
 evaluation/domain/full-reports/full-results.json | 2224 [32m++++++++++++++++++++++++++++++++++++++++++++++++++[m
 evaluation/domain/full-reports/full-review.md    | 3739 [32m+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[m
 evaluation/domain/full-responses/AR-EP-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-EP-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-EP-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-EP-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-II-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-II-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-II-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-PM-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-PM-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-PM-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-PM-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-PM-005.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-SF-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-SF-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-SF-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-TR-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-TR-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-TR-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-TR-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/AR-TR-005.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-EP-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-EP-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-EP-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-EP-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-II-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-II-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-II-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-PM-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-PM-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-PM-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-PM-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-PM-005.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-SF-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-SF-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-SF-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-TR-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-TR-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-TR-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-TR-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/EN-TR-005.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-EP-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-EP-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-EP-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-EP-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-II-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-II-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-II-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-PM-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-PM-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-PM-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-PM-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-PM-005.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-SF-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-SF-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-SF-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-TR-001.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-TR-002.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-TR-003.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-TR-004.json  |   36 [32m+[m
 evaluation/domain/full-responses/FR-TR-005.json  |   36 [32m+[m
 scripts/run_domain_evaluation.py                 |   13 [32m+[m
 64 files changed, 8137 insertions(+)
